name: ateam_map_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  mapbox_gl: ^0.16.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
